parameters:
- name: download_folder
  type: string
- name: download_filename
  type: string
- name: url
  type: string
- name: sha512
  type: string

steps:
- task: Cache@2
  inputs:
    key: '"download" | "$(sha512)" | "$(download_filename)" | "$(uri)"'
    path: "$(download_folder)"
  displayName: Source cache $(download_folder)/$(download_filename)

- powershell: |
    . "azure-pipelines/lib.ps1"

    $d = "$(download_folder)"
    New-Item -ItemType Directory -Force -Path $d
    Get-FileFromInternet "$(url)" "$(sha512)" "$d\$(download_filename)"

  displayName: Download source $(download_folder)/$(download_filename)
